"""The aiosolarfocus command line: `python -m aiosolarfocus <command>`.

The commands that need no controller - `registers` and, later, `plan` - are the
ones that get used, because they turn a table change into something reviewable
before anyone goes near a heating system.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Iterator, Sequence

from .components import COMPONENTS, ComponentSpec
from .const import ApiVersion, Systems
from .layout import Layout
from .registers import RegisterInfo


def _add_controller_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--system", type=Systems, choices=list(Systems), default=Systems.VAMPAIR, help="which heating system (default: %(default)s)")
    parser.add_argument("--api-version", type=ApiVersion.parse, default=ApiVersion.V_26_020, help="controller firmware, as it prints it (default: 26.020)")


def build_parser() -> argparse.ArgumentParser:
    """The whole command line."""
    parser = argparse.ArgumentParser(prog="python -m aiosolarfocus", description=__doc__)
    subcommands = parser.add_subparsers(dest="command", required=True)

    registers = subcommands.add_parser("registers", help="print the register map for a system and firmware, without connecting")
    _add_controller_arguments(registers)
    registers.add_argument("--component", help="only this component, by id")
    registers.add_argument("--markdown", action="store_true", help="emit the generated docs/registers.md")
    registers.set_defaults(run=_run_registers)

    return parser


def _layouts(system: Systems, api_version: ApiVersion, only: str | None) -> Iterator[tuple[ComponentSpec, Layout]]:
    for spec in COMPONENTS:
        if only is not None and spec.id.value != only:
            continue
        if not spec.available(api_version, system):
            continue
        input_base, holding_base = spec.bases(0, api_version)
        yield spec, Layout.resolve(spec.component, api_version, system, input_base, holding_base)


def _row(info: RegisterInfo) -> tuple[str, ...]:
    width = "32-bit" if info.width > 1 else ""
    sign = "signed" if info.signed else "unsigned"
    scale = "" if info.scale == 1.0 else f"x{info.scale:g}"
    bounds = "" if info.bounds is None else f"{info.bounds[0]:g}..{info.bounds[1]:g}"
    return (info.name, info.kind.value, str(info.address), width, sign, scale, info.unit or "", info.access.value, info.since.label, bounds, info.doc)


_HEADINGS = ("register", "table", "address", "width", "sign", "scale", "unit", "access", "since", "range", "document name")


def _run_registers(args: argparse.Namespace) -> int:
    system: Systems = args.system
    api_version: ApiVersion = args.api_version
    sections = [(spec, [_row(resolved.info()) for resolved in layout.registers]) for spec, layout in _layouts(system, api_version, args.component)]

    if args.markdown:
        print(
            f"# Register map\n\nGenerated by `python -m aiosolarfocus registers --markdown`. Do not edit by hand.\n\nSystem **{system.value}**, firmware **{api_version.label}**.\n"
        )
        for spec, rows in sections:
            print(f"## {spec.label.title()} (`{spec.id.value}`)\n")
            print("| " + " | ".join(_HEADINGS) + " |")
            print("|" + "|".join(["---"] * len(_HEADINGS)) + "|")
            for row in rows:
                print("| " + " | ".join(row) + " |")
            print()
        return 0

    print(f"{system.value}, firmware {api_version.label}")
    for spec, rows in sections:
        count = spec.limit(api_version)
        instances = f" (up to {count})" if count > 1 else ""
        print(f"\n{spec.label}{instances} - {len(rows)} registers")
        _print_table(_HEADINGS, rows)
    return 0


def _print_table(headings: Sequence[str], rows: Sequence[Sequence[str]]) -> None:
    widths = [max(len(headings[column]), *(len(row[column]) for row in rows)) if rows else len(headings[column]) for column in range(len(headings))]
    print("  " + "  ".join(heading.ljust(width) for heading, width in zip(headings, widths, strict=True)).rstrip())
    for row in rows:
        print("  " + "  ".join(cell.ljust(width) for cell, width in zip(row, widths, strict=True)).rstrip())


def main(argv: Sequence[str] | None = None) -> int:
    """Run one command."""
    args = build_parser().parse_args(argv)
    exit_code: int = args.run(args)
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
